---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: example-csi-controller
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-csi-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"] # for resize
    verbs: ["update","patch"]
  - apiGroups: ["snapshot.storage.k8s.io"] # for snaptshot
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "update", "watch", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status"]
    verbs: ["update","patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list", "watch","create","delete","update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update","patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-csi-provisioner-role
subjects:
  - kind: ServiceAccount
    name: example-csi-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: example-csi-provisioner-runner
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-csi-attacher-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-csi-attacher-role
subjects:
  - kind: ServiceAccount
    name: example-csi-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: example-csi-attacher-runner
  apiGroup: rbac.authorization.k8s.io

#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: example-csi-resizer-runner
#rules:
#  - apiGroups:
#      - ""
#    resources:
#      - persistentvolumes
#    verbs:
#      - get
#      - list
#      - watch
#      - update
#      - patch
#  - apiGroups:
#      - ""
#    resources:
#      - persistentvolumeclaims
#    verbs:.
#      - get
#      - list
#      - watch
#  - apiGroups:
#      - ""
#    resources:
#      - persistentvolumeclaims/status
#    verbs:
#      - update
#      - patch
#  - apiGroups:
#      - ""
#    resources:
#      - events
#    verbs:
#      - list
#      - watch
#      - create
#      - update
#      - patch
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-csi-node
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-csi-driver-registrar-runner
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-csi-driver-registrar-role
subjects:
  - kind: ServiceAccount
    name: example-csi-node
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: example-csi-driver-registrar-runner
  apiGroup: rbac.authorization.k8s.io

